### ISSUE TITLE
<hr> aren't supported?

### ISSUE THREAD

**Issue by math2001** [markdowncss/splendor#2]
This is a pretty neat CSS, loving it! But, I had to tweak it for the `hr`s... Otherwise you get something really weird... 

Could you add support for them? That'd be just great.

Thanks anyway 😉 

Matt

**Comment by ZebTheWizard** [comment]
it's because he forgot to include `:not(hr)` 
```css
p,
*:not(div):not(hr):not(img):not(body):not(html):not(li):not(blockquote):not(p) {
  margin: 1rem auto 1rem;
  max-width: 36rem;
  padding: .25rem;
}
```
